#pragma once

#define PI 3.141592f
#define DEG_TO_RAD(deg) (deg * (PI / 180.0f))

#define MIN(a, b) (((a) < (b)) ? (a) : (b))

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define TILE_SIZE 32

#define SCREEN_TILE_X (SCREEN_WIDTH / TILE_SIZE)
#define SCREEN_TILE_Y (SCREEN_HEIGHT / TILE_SIZE)

// CAMERA
#define CAMERA_ZOOM_RATIO 1.1f

// MAP
#define TILE_FLOOR 0
#define TILE_WALL 1
#define TILE_DOOR 2
#define TILE_OBSTACLE 3

#define WALL_THICKNESS 5

#define WAITINGMAP_ROWS (SCREEN_HEIGHT / TILE_SIZE)
#define WAITINGMAP_COLS (SCREEN_WIDTH / TILE_SIZE)

#define HALLWAYMAP_ROWS (int)(WAITINGMAP_ROWS * 3.0f)
#define HALLWAYMAP_COLS (int)(WAITINGMAP_COLS * 1.0f)

#define BOSSMAP_ROWS (int)(WAITINGMAP_ROWS * 2.0f)
#define BOSSMAP_COLS (int)(WAITINGMAP_COLS * 2.0f)

#define WAITING_Y   0
#define HALLWAY1_Y  (WAITINGMAP_ROWS * TILE_SIZE)
#define BOSS1_Y     (HALLWAY1_Y + HALLWAYMAP_ROWS * TILE_SIZE)
#define HALLWAY2_Y  (BOSS1_Y   + BOSSMAP_ROWS    * TILE_SIZE)
#define BOSS2_Y     (HALLWAY2_Y + HALLWAYMAP_ROWS * TILE_SIZE)
#define HALLWAY3_Y  (BOSS2_Y   + BOSSMAP_ROWS    * TILE_SIZE)
#define BOSS3_Y     (HALLWAY3_Y + HALLWAYMAP_ROWS * TILE_SIZE)

#define MAX_MAP_ROWS 512
#define MAX_MAP_COLS 512
#define MAX_DOORS 16

// PLAYER
#define PLAYER_WIDTH 32
#define PLAYER_HEIGHT 36
#define PLAYER_HITBOX_WIDTH 24
#define PLAYER_HITBOX_HEIGHT 46

#define PLAYER_HP 100
#define PLAYER_MP 100
#define PLAYER_SPEED 20.5f

#define PLAYER_INVINCIBLE_TIME 60
#define PLAYER_DEATH_TIME 120

// ENEMY
#define ENEMY_WIDTH (TILE_SIZE * 4)
#define ENEMY_HEIGHT (TILE_SIZE * 4)
#define ENEMY_HITBOX_WIDTH 34
#define ENEMY_HITBOX_HEIGHT 68
#define ENEMY_HP 30
#define ENEMY_LIMIT 1

#define ENEMY_COLS_SPAWN_MARGIN 20
#define ENEMY_ROWS_SPAWN_MARGIN 10

#define ENEMY_MOVE_TIME 120
#define ENEMY_DEATH_TIME 120

#define ENEMY_CHASE_RANGE 200.0f
#define ENEMY_SPEED 2.5f
#define ENEMY_CONTACT_DAMAGE 5
#define ENEMY_STOP_DISTANCE 30.0f

#define CAT_PAW_WIDTH 32
#define CAT_PAW_HEIGHT 32
#define CAT_PAW_HITBOX_W 12
#define CAT_PAW_HITBOX_H 12
#define CAT_PAW_SPEED 12.0f
#define CAT_PAW_DAMAGE 10
#define CAT_PAW_LIMIT 10
#define CAT_PAW_INTERVAL 180

// BOSS
#define BOSS_WIDTH (TILE_SIZE * 3)
#define BOSS_HEIGHT (TILE_SIZE * 3)
#define BOSS_HP 500
#define BOSS_PAW_SIZE 32
#define BOSS_HITBOX_WIDTH (BOSS_WIDTH - 20)
#define BOSS_HITBOX_HEIGHT (BOSS_HEIGHT - 20)
#define BOSS_PAW_SPEED 10.0f
#define BOSS_PAW_INTERVAL 180
#define BOSS_PAW_LIMIT 1000
#define BOSS_CIRCULARPAWS_COUNT 32		// 원형 탄막 개수

#define DASH_WARN_TILES 100
#define DASH_WARN_INTERVAL 100
#define DASH_SPEED 18.0f
#define DASH_INTERVAL 50

#define BOSS_ATTACK_INTERVAL 60
#define BOSS_SKILL_CHARGE_TIME 120				// 총 2초 (20프레임 * 6단계)
#define BOSS_SKILL_CHARGE_UPDATE_FRAME 6		// 0.1초(6프레임)마다 프레임 변경

#define BOSS_MOVE_SPEED 3.0f
#define BOSS_MOVE_INTERVAL 180

#define BOSS_CHASE_SPEED 5.0f

#define BOSS_JUMP_WARN_INTERVAL 100
#define BOSS_JUMP_LAND_SIZE (BOSS_WIDTH * 2)
#define BOSS_JUMP_LAND_SIZE_W_RATIO 0.8f
#define BOSS_JUMP_LAND_SIZE_H_RATIO 0.4f
#define JUMPWARN_Y_OFFSET 50.0f

#define BOSS_CONTACT_DAMAGE    20
#define BOSS_DASH_DAMAGE 25
#define BOSS_JUMP_DAMAGE 30

#define BOSS_NORMAL_KNOCKBACK  10.0f
#define BOSS_DASH_KNOCKBACK    30.0f
#define BOSS_JUMP_KNOCKBACK    25.0f

#define BOSS_SPIRAL_COUNT      36      // 회오리 한 바퀴 발사 수
#define BOSS_SPIRAL_INTERVAL   4       // 발사 간격 (프레임)
#define BOSS_SPIRAL_ROTATIONS  3       // 총 회전 수

#define BOSS_DOUBLE_DASH_DELAY  10     // 첫 대시 종료 후 두 번째 대시까지 딜레이 (프레임)

#define BOSS_RANDOM_CIRCULARPAWS_COUNT 96


// BULLET
#define BULLET_MAX 50
#define BULLET_WIDTH 64
#define BULLET_HEIGHT 64
#define BULLET_HITBOX_WIDTH 28
#define BULLET_HITBOX_HEIGHT 28
#define BULLET_SPEED 20.5f
#define BULLET_DAMAGE 10
#define KNOCKBACK_FORCE 6.0f
#define KNOCKBACK_TIME 16

// PLAYER SKILL & FIRE RATE
#define PLAYER_FIRE_COOLDOWN 15				// 기본 발사 쿨타임 (프레임)

#define SKILL_Q_MP 20
#define SKILL_Q_COOLDOWN 300				// Q 스킬 쿨타임 (5초)

#define SKILL_E_MP 10
#define BOOST_DURATION 300					// 부스트 지속 시간 (5초)
#define BOOST_COOLDOWN 600					// 부스트 쿨타임 (10초)
#define BOOST_FIRE_RATE_MULTIPLIER 0.5f		// 부스트 시 공격 쿨타임 배율 (낮을수록 빠름)
#define BOOST_SPEED_MULTIPLIER 1.5f			// 부스트 시 이동속도 배율

#define SKILL_R_MP 30
#define SKILL_R_COOLDOWN 480				// R 스킬 쿨타임 (8초)
#define CHURU_WIDTH 64
#define CHURU_HEIGHT 64
#define CHURU_SPEED 10.0f
#define CHURU_MAX_DIST 300.0f
#define CHURU_DURATION 300					// 바닥에 머무는 시간 (5초)
#define CHURU_AGGRO_RANGE 400.0f			// 어그로 범위
#define CHURU_MAX 2

#define ITEM_ONE_COOLDOWN 900
#define ITEM_TWO_COOLDOWN 720

#define POTION_LIMIT 5

// UI
#define TITLE_START_HEIGHT_MARGIN 0.65f
#define TITLE_EXIT_HEIGHT_MARGIN 0.80f

#define HPBAR_FRAME_WIDTH_MARGIN 192
#define HPBAR_FRAME_HEIGHT_MARGIN 128
#define MPBAR_FRAME_WIDTH_MARGIN 192
#define MPBAR_FRAME_HEIGHT_MARGIN 128

#define HPBAR_WIDTH_MARGIN 192
#define HPBAR_HEIGHT_MARGIN 128
#define MPBAR_WIDTH_MARGIN 192
#define MPBAR_HEIGHT_MARGIN 128

#define Q_ICON_WIDTH_MARGIN 224 + 7
#define Q_ICON_HEIGHT_MARGIN 64
#define E_ICON_WIDTH_MARGIN 160 + 7
#define E_ICON_HEIGHT_MARGIN 64
#define R_ICON_WIDTH_MARGIN 96 + 7
#define R_ICON_HEIGHT_MARGIN 64

#define HP_POTION_WIDTH_MARGIN 96 - 7
#define HP_POTION_HEIGHT_MARGIN 64
#define MP_POTION_WIDTH_MARGIN 160 - 7
#define MP_POTION_HEIGHT_MARGIN 64

#define GUI_LOGO_HEIGHT_MARGIN 128

#define PAUSE_PLAY_BUTTON_BG_HEIGHT_MARGIN 145