#pragma once

#define TILE_SIZE 32

#define PLAYER_SIZE 32

#define ENEMY_SIZE 32
#define ENEMY_LIMIT 60

#define BOSS_SIZE (32 * 3)

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define SCREEN_TILE_X (SCREEN_WIDTH / TILE_SIZE)
#define SCREEN_TILE_Y (SCREEN_HEIGHT / TILE_SIZE)

// MAP
#define TILE_FLOOR 0
#define TILE_WALL 1
#define TILE_DOOR 2

#define WAITINGMAP_ROWS (SCREEN_HEIGHT / TILE_SIZE)
#define WAITINGMAP_COLS (SCREEN_WIDTH / TILE_SIZE)

#define HALLWAYMAP_ROWS (int)(WAITINGMAP_ROWS * 1.5f)
#define HALLWAYMAP_COLS (int)(WAITINGMAP_COLS * 1.5f)

#define BOSSMAP_ROWS (int)(WAITINGMAP_ROWS * 2.0f)
#define BOSSMAP_COLS (int)(WAITINGMAP_COLS * 2.0f)

#define WAITING_X   0
#define HALLWAY1_X  (WAITINGMAP_COLS * TILE_SIZE)
#define BOSS1_X     (HALLWAY1_X + HALLWAYMAP_COLS * TILE_SIZE)
#define HALLWAY2_X  (BOSS1_X   + BOSSMAP_COLS    * TILE_SIZE)
#define BOSS2_X     (HALLWAY2_X + HALLWAYMAP_COLS * TILE_SIZE)
#define HALLWAY3_X  (BOSS2_X   + BOSSMAP_COLS    * TILE_SIZE)
#define BOSS3_X     (HALLWAY3_X + HALLWAYMAP_COLS * TILE_SIZE)

#define MAX_MAP_ROWS 128
#define MAX_MAP_COLS 256
#define MAX_DOORS 16

// ENEMY
#define ENEMY_COLS_SPAWN_MARGIN 20
#define ENEMY_ROWS_SPAWN_MARGIN 5

#define ENEMY_CHASE_RANGE 200.0f
#define ENEMY_SPEED 2.0f

#define STONE_SIZE 10
#define STONE_SPEED 5.0f
#define STONE_LIMIT (ENEMY_LIMIT * 2)
#define STONE_INTERVAL 180
